import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SYSTEM_PROMPT = `You are Jackye Clayton's voice in Ask Jackye on Who Do I Work For. Career intelligence strategist and truth-teller. You are in the room, not on a slide. You have run hiring and TA at scale; you are not theorizing.

HOW YOU WRITE
- Direct, conversational, controlled urgency. Use I and we. Talk to the user as you.
- Short paragraphs. Mostly short or medium sentences. Fragments are fine ("Not good enough." "That's the gap.").
- Human and slightly raw. Clear beats impressive. If it sounds like LinkedIn filler or marketing, strip it.
- NEVER use em dashes. Use commas, periods, colons, or parentheses instead.
- NEVER use generic assistant openers: no "Great question", "I'd be happy to help", "Absolutely", "Certainly", "I'd love to".
- Avoid AI tells: no "It's important to note", "Furthermore", "Moreover", "delve", "landscape", "robust", "leverage" as empty jargon (you may use "leverage" only when you mean real bargaining power).
- Do not do symmetrical "on one hand / on the other" padding. Do not stack three parallel clauses for rhythm.
- End with a clear next move for the user (what to ask, check, or decide).

HOW YOU THINK (FLOW NATURALLY; DO NOT LABEL THESE AS SECTION HEADINGS)
Move through: what is happening, what it means, what people usually miss, what we do next. No printed labels like "What it means" unless the user asked for an outline.

SUBSTANCE
- Ground answers in receipts: public filings, workforce signals, money trails, transparency gaps, leadership patterns, legal and labor signals when relevant.
- Say when data is missing. Separate evidence from inference.
- You are not a lawyer, therapist, or financial advisor. No legal diagnoses. Point to professionals when needed.

WHEN THEY WANT A DEEP READ ON ONE COMPANY
- Plain language. You may use a few ## headers if it helps scan, no emoji in headings, no fake report metadata ("Generated by", version numbers).
- Tables only when numbers need comparing. Otherwise prose and tight bullets.
- Keep the same voice throughout. Close with one concrete next step.

VOCABULARY (USE WHEN IT FITS, NOT AS A CHECKLIST)
Receipts, signals, audit, risk, pattern, follow the money, know before you go, what they are not telling you, design failure (when the system is broken, not the person).

You are skeptical of systems that hide reality. You are on the side of the person using the product. You are not cynical.`;

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // --- Authentication gate ---
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(
        JSON.stringify({ error: "Sign in to access the Intelligence Advisor. Your session is required." }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;

    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });

    const token = authHeader.replace("Bearer ", "");
    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
    if (claimsError || !claimsData?.claims?.sub) {
      return new Response(
        JSON.stringify({ error: "Your session has expired. Please sign in again." }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const userId = claimsData.claims.sub;
    console.log(`[INTELLIGENCE-ADVISOR] Authenticated user: ${userId}`);
    // --- End authentication gate ---

    const { messages, companyContext, companyId } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("AI gateway key is not configured");

    // --- Enrich with company data if companyId provided ---
    const systemMessages: any[] = [{ role: "system", content: SYSTEM_PROMPT }];

    if (companyId) {
      try {
        const serviceClient = createClient(supabaseUrl, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

        // Parallel data fetches for intelligence enrichment
        const [
          companyRes,
          signalsRes,
          execsRes,
          boardRes,
          eeo1Res,
          disclosuresRes,
          courtRes,
          benchmarkRes,
        ] = await Promise.all([
          serviceClient.from("companies").select("name, industry, state, employee_count, civic_footprint_score, confidence_rating, lobbying_spend, total_pac_spending, government_contracts, subsidies_received, effective_tax_rate, revenue").eq("id", companyId).single(),
          serviceClient.from("company_values_signals").select("value_category, signal_summary, confidence, created_at").eq("company_id", companyId).order("created_at", { ascending: false }).limit(30),
          serviceClient.from("company_executives").select("name, title, verification_status").eq("company_id", companyId).is("departed_at", null).limit(15),
          serviceClient.from("board_members").select("name, title, is_independent, committees").eq("company_id", companyId).is("departed_at", null).limit(15),
          serviceClient.from("company_eeo1_data").select("job_category, total_employees, female_count, male_count, white_count, black_count, hispanic_count, asian_count, report_year").eq("company_id", companyId).order("report_year", { ascending: false }).limit(10),
          serviceClient.from("company_diversity_disclosures").select("disclosure_type, year, is_published, notes").eq("company_id", companyId),
          serviceClient.from("company_court_cases").select("case_name, case_type, nature_of_suit, status, date_filed, summary").eq("company_id", companyId).limit(10),
          serviceClient.from("company_benchmarks").select("*").eq("company_id", companyId).single(),
        ]);

        const enrichment: Record<string, any> = {};
        if (companyRes.data) enrichment.company = companyRes.data;
        if (signalsRes.data?.length) enrichment.workforceSignals = signalsRes.data;
        if (execsRes.data?.length) enrichment.executives = execsRes.data;
        if (boardRes.data?.length) enrichment.boardMembers = boardRes.data;
        if (eeo1Res.data?.length) enrichment.eeo1Data = eeo1Res.data;
        if (disclosuresRes.data?.length) enrichment.diversityDisclosures = disclosuresRes.data;
        if (courtRes.data?.length) enrichment.courtCases = courtRes.data;
        if (benchmarkRes.data) enrichment.industryBenchmarks = benchmarkRes.data;

        if (Object.keys(enrichment).length > 0) {
          systemMessages.push({
            role: "system",
            content: `Live company data for this session (JSON). Use it like receipts: cite numbers, name contradictions, say when something is missing.\n\n${JSON.stringify(enrichment, null, 2)}`,
          });
        }
      } catch (enrichErr: any) {
        console.error("[INTELLIGENCE-ADVISOR] Enrichment failed:", enrichErr);
        // Continue without enrichment — degrade gracefully
      }
    } else if (companyContext) {
      systemMessages.push({
        role: "system",
        content: `Company context for this chat (JSON). Use it when it helps. Say what's missing.\n${JSON.stringify(companyContext, null, 2)}`,
      });
    }

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [...systemMessages, ...messages],
        stream: true,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Intelligence systems are at capacity. Try again in a moment." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "AI usage limit reached. Please add credits to continue." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const t = await response.text();
      console.error("AI gateway error:", response.status, t);
      return new Response(JSON.stringify({ error: "Intelligence system error" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(response.body, {
      headers: { ...corsHeaders, "Content-Type": "text/event-stream" },
    });
  } catch (e: any) {
    console.error("intelligence-advisor error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
