-- ============================================================================
-- 10-seed-receipts-companies.sql
-- Seed data for the 10 WDIWF Receipts investigation companies
-- All data sourced from research files with real PAC, lobbying, and contract numbers
-- Idempotent: uses INSERT ... ON CONFLICT (slug) DO UPDATE
-- Run in Supabase SQL Editor
-- ============================================================================

-- ============================================================================
-- META (Facebook / Meta Platforms)
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Meta Platforms',
  'meta',
  'Technology',
  'CA',
  82,
  341607,
  'high',
  'active',
  '2026-03-24',
  'META',
  true,
  true,
  24400000,
  '67,000',
  'Parent company of Facebook, Instagram, WhatsApp, and Threads, and a major investor in AI and metaverse technologies.',
  '$135B',
  4.5,
  72,
  'Meta talks a big game about connecting the world, but their Receipts tell a different story. $24.4M in lobbying spend, a PAC writing checks to both sides, and a track record of saying one thing publicly while funding the opposite privately. Job seekers should know: the culture has shifted hard toward efficiency metrics and away from the mission-driven ethos that once defined Facebook.',
  'https://about.meta.com',
  'https://www.metacareers.com',
  ARRAY['big-tech', 'social-media', 'ai', 'advertising'],
  NULL,
  false,
  'Public Corporation',
  'Major tech employer with significant layoffs in 2022-2023; year of efficiency reshaped culture toward leaner teams and higher performance expectations.',
  'Billions of users rely on Meta platforms daily; privacy practices, content moderation, and algorithmic transparency directly affect consumers.',
  'Social Media & Advertising',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- GOOGLE (Alphabet Inc.)
-- PAC: $1,902,225 | Lobbying 2024: $14,860,000 | FEC: C00428623
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Alphabet Inc. (Google)',
  'google',
  'Technology',
  'CA',
  85,
  1902225,
  'high',
  'active',
  '2026-03-24',
  'GOOGL',
  true,
  true,
  14860000,
  '182,000',
  'Parent company of Google, the dominant search engine, cloud platform, and AI research leader with operations spanning advertising, hardware, and autonomous vehicles.',
  '$307B',
  5.0,
  75,
  'Google wants you to believe they are still the "don''t be evil" company. The Receipts show $14.8M in annual lobbying, a bipartisan PAC hedging all bets, and DEI goals quietly scrubbed from the 10-K after the 2025 executive order. They cut 25,000+ jobs while hiring aggressively for AI. If you are joining Google today, understand that the company you read about in college no longer exists — it is an ad-revenue and AI-contracts machine.',
  'https://abc.xyz',
  'https://careers.google.com',
  ARRAY['big-tech', 'ai', 'advertising', 'cloud'],
  200000000,
  false,
  'Public Corporation',
  'Cut 25,000+ jobs since 2023 while expanding AI teams; eliminated aspirational diversity hiring goals in February 2025; net headcount roughly stable due to AI rebalancing.',
  'Google Search, YouTube, Gmail, Android, and Chrome touch billions of users daily; AI integration into search and data collection practices have major consumer privacy implications.',
  'Search & Cloud Computing',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- AMAZON
-- PAC: $1,583,307 | Lobbying 2024: $19,140,000 | FEC: C00360354
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Amazon',
  'amazon',
  'Technology',
  'WA',
  90,
  1583307,
  'high',
  'active',
  '2026-03-24',
  'AMZN',
  true,
  true,
  19140000,
  '1,500,000',
  'Global e-commerce, cloud computing (AWS), and logistics giant, and one of the largest private employers in the United States.',
  '$575B',
  3.5,
  80,
  'Amazon is the company where the gap between the careers page and reality is widest. They spend $19M+ per year lobbying, have laid off over 100,000 workers since 2022, and dissolved their DEI programs in December 2024 — before the executive order even dropped. The WARN Act filings paint a picture the recruiter will not. If you are considering Amazon, ask hard questions about team stability and which division is next.',
  'https://www.amazon.com',
  'https://www.amazon.jobs',
  ARRAY['big-tech', 'e-commerce', 'cloud', 'logistics'],
  1000000000,
  false,
  'Public Corporation',
  'Largest private-sector employer with 1.5M+ workers; 100,000+ layoffs since 2022; WARN filings in WA show ongoing corporate reductions; DEI programs dissolved December 2024; warehouse injury rates double the industry average.',
  'Dominates online retail, grocery delivery, streaming, and smart home devices; AWS powers a significant portion of the internet; labor and data practices affect hundreds of millions of consumers.',
  'E-Commerce & Cloud',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- MICROSOFT
-- PAC: $2,061,317 | Lobbying 2024: $10,400,000 | FEC: C00227546
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Microsoft',
  'microsoft',
  'Technology',
  'WA',
  84,
  2061317,
  'high',
  'active',
  '2026-03-24',
  'MSFT',
  true,
  true,
  10400000,
  '228,000',
  'Global technology company behind Windows, Azure cloud, Office 365, LinkedIn, and a major investor in OpenAI.',
  '$236B',
  4.0,
  78,
  'Microsoft plays the long game better than anyone. They removed DEI from performance reviews, stopped publishing their diversity report, and quietly cut 35,000+ workers — all while positioning as the responsible AI company. Seventy-five percent of their lobbyists are former government officials. The OneGov deal alone shows how deeply intertwined they are with federal spending. Candidates should look past the brand and into which division is actually growing.',
  'https://www.microsoft.com',
  'https://careers.microsoft.com',
  ARRAY['big-tech', 'ai', 'cloud', 'enterprise-software'],
  6000000000,
  false,
  'Public Corporation',
  'Cut 35,000+ jobs since 2023 including large gaming layoffs; 55 WARN Act notices on record; removed DEI from performance reviews November 2025; stopped publishing annual diversity report; 75% of lobbyists are revolving door hires.',
  'Windows, Office, Azure, LinkedIn, and Xbox reach billions of users and businesses; AI integration via Copilot across all products raises questions about data use and workforce displacement.',
  'Enterprise Software & Cloud',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- BOEING
-- PAC: $5,420,306 | Lobbying 2024: $11,930,000 | FEC: C00142711
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Boeing',
  'boeing',
  'Aerospace & Defense',
  'VA',
  92,
  5420306,
  'high',
  'active',
  '2026-03-24',
  'BA',
  true,
  true,
  11930000,
  '170,000',
  'Aerospace and defense manufacturer of commercial aircraft, military systems, satellites, and space launch vehicles.',
  '$78B',
  2.5,
  85,
  'Boeing is the case study in what happens when lobbying replaces engineering culture. They have the largest PAC of any company we have investigated — $5.4M — and 593 WARN Act filings since 1990. They dismantled their DEI department in October 2024, while 72% of their lobbyists came through the revolving door. Meanwhile, door plugs are blowing off planes. If you are an engineer considering Boeing, the safety culture problems are not hypothetical — they are documented by the FAA and NTSB.',
  'https://www.boeing.com',
  'https://jobs.boeing.com',
  ARRAY['aerospace', 'defense', 'manufacturing'],
  12800000000,
  false,
  'Public Corporation',
  'Cut 25,000+ jobs since 2024 (10% of workforce); 593 WARN Act filings since 1990; dismantled global DEI department October 2024; safety culture under FAA and NTSB scrutiny; 72% of lobbyists are revolving door hires; whistleblower retaliation concerns.',
  'Millions fly on Boeing aircraft daily; safety record directly affects consumer welfare; defense products funded by taxpayers; supply chain touches thousands of communities.',
  'Aerospace & Defense Manufacturing',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- BOOZ ALLEN HAMILTON
-- PAC: $359,654 | Lobbying 2024: $1,670,000 | FEC: C00709816
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Booz Allen Hamilton',
  'booz-allen-hamilton',
  'Consulting',
  'VA',
  78,
  359654,
  'high',
  'active',
  '2026-03-24',
  'BAH',
  true,
  true,
  1670000,
  '35,000',
  'Management and IT consulting firm specializing in analytics, digital, engineering, and cybersecurity for government agencies and defense clients.',
  '$11B',
  3.0,
  70,
  'Booz Allen is a federal contracting machine — 98% of revenue comes from government work. They dismantled their entire DEI department in February 2025, banned non-birth pronoun usage, and laid off 7,400+ workers. The Treasury canceled $21M in contracts after the Littlejohn data breach scandal. When nearly all your revenue depends on government approval, policy compliance is not optional — it is the business model. Candidates with clearances should understand that your career here rises and falls with federal spending priorities.',
  'https://www.boozallen.com',
  'https://careers.boozallen.com',
  ARRAY['consulting', 'defense', 'cybersecurity', 'government-services'],
  9400000000,
  false,
  'Public Corporation',
  'Laid off 7,400+ workers in 2025-2026 tied to federal contract slowdowns; dismantled DEI department February 2025 including banning non-birth pronouns; 98% revenue from government contracts creates high exposure to policy shifts; insider breach scandals (Snowden, Littlejohn).',
  'Indirectly affects millions through government technology systems, defense intelligence, and cybersecurity infrastructure; Treasury data breach exposed taxpayer information.',
  'Government IT Consulting',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- ACCENTURE
-- PAC: $175,476 | Lobbying 2024: $2,980,000 | FEC: C00300707
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Accenture',
  'accenture',
  'Consulting',
  'NY',
  72,
  175476,
  'high',
  'active',
  '2026-03-24',
  'ACN',
  true,
  true,
  2980000,
  '779,000',
  'Global professional services and consulting firm specializing in digital transformation, cloud, security, and AI implementation across industries.',
  '$65B',
  3.5,
  65,
  'Accenture is the quiet giant. They sunset their 2017 diversity goals in February 2025, laid off 50,000+ workers in the name of AI reskilling, and spent $865M on restructuring. Fifty-seven percent of their lobbyists are revolving door. Their federal consulting arm — Accenture Federal Services — pulls in billion-dollar contracts. If you are joining Accenture, know that "reskill or exit" is not a slogan — it is the actual policy, and the bench is thinner than it has ever been.',
  'https://www.accenture.com',
  'https://www.accenture.com/us-en/careers',
  ARRAY['consulting', 'technology-services', 'government-services', 'ai'],
  1600000000,
  false,
  'Public Corporation',
  'Cut 50,000+ workers since 2023 with $865M restructuring spend; sunset global diversity goals February 2025; paused external diversity surveys; AI-driven "reskill or exit" policy displaces non-billable staff; 57% revolving door lobbyists.',
  'Implements technology systems for Fortune 500 companies and governments worldwide; consulting recommendations shape corporate policies that affect workers across industries.',
  'Professional Services & Consulting',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- VERIZON
-- PAC: $2,296,056 | Lobbying 2024: $11,380,000 | FEC: C00186288
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'Verizon',
  'verizon',
  'Telecommunications',
  'NY',
  86,
  2296056,
  'high',
  'active',
  '2026-03-24',
  'VZ',
  true,
  true,
  11380000,
  '105,000',
  'Leading telecommunications company providing wireless, broadband, and enterprise networking services across the United States.',
  '$134B',
  3.0,
  76,
  'Verizon literally traded their DEI program for a merger. They wrote a letter to the FCC dismantling all diversity policies to get the $20B Frontier acquisition approved. Then they announced the largest layoffs in company history — 13,000+ in November 2025 — and started converting retail stores to franchises. Seventy-four percent of their lobbyists are former government officials. This is a company where regulatory capture is the strategy, not a side effect. Workers should expect continued restructuring.',
  'https://www.verizon.com',
  'https://www.verizon.com/about/careers',
  ARRAY['telecom', 'wireless', 'broadband', 'enterprise'],
  NULL,
  false,
  'Public Corporation',
  'Cut 40,000+ workers since 2023 with 13,000+ announced November 2025 (largest ever); 61 WARN Act notices on record; dismantled all DEI policies May 2025 to secure FCC merger approval; converting retail stores to franchises eliminates direct employment; 74% revolving door lobbyists.',
  'Provides wireless and internet service to over 100 million connections; network reliability and pricing directly affect consumers; spectrum lobbying shapes broadband access policy.',
  'Wireless & Broadband',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- T-MOBILE
-- PAC: $1,336,169 | Lobbying 2024: $9,500,000 | FEC: C00361758
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'T-Mobile',
  't-mobile',
  'Telecommunications',
  'WA',
  79,
  1336169,
  'high',
  'active',
  '2026-03-24',
  'TMUS',
  true,
  true,
  9500000,
  '71,000',
  'Third-largest US wireless carrier formed from the T-Mobile and Sprint merger, providing mobile and home internet services.',
  '$80B',
  3.5,
  68,
  'T-Mobile built the "un-carrier" brand on being different, but the Receipts tell a familiar story. They eliminated their DEI teams in July 2025, spend $9.5M annually on lobbying with 81% revolving door lobbyists, and have filed 20+ WARN Act notices. The Sprint merger integration is still producing layoffs years later. Their $2.67B Navy contract shows the real growth strategy is government, not just consumers. The culture that John Legere built is being quietly corporate-ified under new leadership.',
  'https://www.t-mobile.com',
  'https://www.t-mobile.com/careers',
  ARRAY['telecom', 'wireless', 'defense'],
  2670000000,
  false,
  'Public Corporation',
  'Cut 12,000+ workers since 2023 including ongoing Sprint merger integration layoffs; 20+ WARN Act notices; eliminated DEI roles and teams July 2025 under FCC pressure; 81% revolving door lobbyists; post-merger culture shift from un-carrier startup ethos to traditional corporate.',
  'Serves 100M+ wireless customers; home internet expanding to underserved areas; data breach history affects consumer trust; pricing and coverage decisions shape rural broadband access.',
  'Wireless Telecommunications',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;

-- ============================================================================
-- AT&T
-- PAC: $2,440,629 | Lobbying 2024: $12,050,000 | FEC: C00109017
-- ============================================================================
INSERT INTO public.companies (
  name, slug, industry, state, civic_footprint_score, total_pac_spending,
  confidence_rating, record_status, last_reviewed, ticker, is_publicly_traded,
  corporate_pac_exists, lobbying_spend, employee_count, description, revenue,
  career_intelligence_score, insider_score, jackye_insight, website_url,
  careers_url, category_tags, government_contracts, is_startup, legal_status,
  worker_relevance, consumer_relevance, sub_industry, vetted_status, identity_matched
) VALUES (
  'AT&T',
  'att',
  'Telecommunications',
  'TX',
  87,
  2440629,
  'high',
  'active',
  '2026-03-24',
  'T',
  true,
  true,
  12050000,
  '150,000',
  'Largest telecommunications company in the US by revenue, providing wireless, broadband, fiber, and enterprise networking services nationwide.',
  '$122B',
  3.0,
  77,
  'AT&T is the original Ma Bell, and they still operate like a monopoly with a lobbying budget. At $12M per year in lobbying and 134 WARN Act filings on record, this is a company that manages its workforce through cycles of expansion and contraction. They eliminated all DEI roles in December 2025 and dropped out of HRC participation entirely. The spectrum lobbying tells you where the money goes — and who benefits. Workers in legacy divisions should be prepared for continued restructuring as the company bets on fiber and 5G.',
  'https://www.att.com',
  'https://www.att.jobs',
  ARRAY['telecom', 'wireless', 'broadband', 'enterprise'],
  146000000,
  false,
  'Public Corporation',
  '134 WARN Act filings on record with ongoing layoffs across multiple states; eliminated all DEI roles December 2025; dropped HRC participation; heavy spectrum lobbying aligns with FCC regulatory strategy; workforce declining as company shifts from legacy to fiber/5G.',
  'Provides phone, internet, and TV services to tens of millions of households; first-net public safety network serves first responders; spectrum and broadband policy affects access for underserved communities.',
  'Telecommunications & Broadband',
  'verified',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry,
  state = EXCLUDED.state,
  civic_footprint_score = EXCLUDED.civic_footprint_score,
  total_pac_spending = EXCLUDED.total_pac_spending,
  confidence_rating = EXCLUDED.confidence_rating,
  record_status = EXCLUDED.record_status,
  last_reviewed = EXCLUDED.last_reviewed,
  ticker = EXCLUDED.ticker,
  is_publicly_traded = EXCLUDED.is_publicly_traded,
  corporate_pac_exists = EXCLUDED.corporate_pac_exists,
  lobbying_spend = EXCLUDED.lobbying_spend,
  employee_count = EXCLUDED.employee_count,
  description = EXCLUDED.description,
  revenue = EXCLUDED.revenue,
  career_intelligence_score = EXCLUDED.career_intelligence_score,
  insider_score = EXCLUDED.insider_score,
  jackye_insight = EXCLUDED.jackye_insight,
  website_url = EXCLUDED.website_url,
  careers_url = EXCLUDED.careers_url,
  category_tags = EXCLUDED.category_tags,
  government_contracts = EXCLUDED.government_contracts,
  is_startup = EXCLUDED.is_startup,
  legal_status = EXCLUDED.legal_status,
  worker_relevance = EXCLUDED.worker_relevance,
  consumer_relevance = EXCLUDED.consumer_relevance,
  sub_industry = EXCLUDED.sub_industry,
  vetted_status = EXCLUDED.vetted_status,
  identity_matched = EXCLUDED.identity_matched;
